### ISSUE TITLE
An empty PR description fails the build without explanation

### ISSUE THREAD

**Issue by cerihughes** [spotify/HubFramework#266]
The reason for the failure is swallowed by either Danger or Fastlane, making it *very* difficult to figure out what the problem is.

**Comment by rastersize** [comment]
Output in the build log:
```
The command "fastlane ci_all" exited with 0.
10.07s$ if [[ "$RUN_DANGER" == "YES" ]]; then fastlane validate_changes; fi
+-------------------------+---------+---------+
|                Used plugins                 |
+-------------------------+---------+---------+
| Plugin                  | Version | Action  |
+-------------------------+---------+---------+
| fastlane-plugin-trainer | 0.2.0   | trainer |
+-------------------------+---------+---------+
[16:37:29]: ---------------------------
[16:37:29]: --- Step: opt_out_usage ---
[16:37:29]: ---------------------------
[16:37:29]: Disabled upload of used actions
[16:37:29]: ------------------------------
[16:37:29]: --- Step: default_platform ---
[16:37:29]: ------------------------------
[16:37:31]: Driving the lane 'ios validate_changes' 🚀
[16:37:31]: --------------------
[16:37:31]: --- Step: danger ---
[16:37:31]: --------------------
[16:37:31]: $ bundle exec danger
[16:37:35]: ▸ bundler: failed to load command: danger (/Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/bin/danger)
[16:37:35]: ▸ RuntimeError: Commit 7e3bac59 doesn't exist. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed.
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/scm_source/git_repo.rb:58:in `raise_if_we_cannot_find_the_commit'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/scm_source/git_repo.rb:43:in `ensure_commitish_exists!'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/request_sources/github.rb:77:in `setup_danger_branches'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/danger_core/environment_manager.rb:57:in `ensure_danger_branches_are_setup'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/danger_core/dangerfile.rb:258:in `setup_for_running'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/danger_core/dangerfile.rb:269:in `run'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/danger_core/executor.rb:27:in `run'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/lib/danger/commands/runner.rb:66:in `run'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/gems/danger-4.0.1/bin/danger:5:in `<top (required)>'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/bin/danger:23:in `load'
[16:37:35]: ▸ /Users/travis/build/spotify/HubFramework/vendor/bundle/ruby/2.2.0/bin/danger:23:in `<top (required)>'
```

So it would seem that Danger was trying to find commit `7e3bac59` which wasn’t in the #257 PR from what I can tell. Much weird!

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
